SELECT TOP (1000) [customer_id]
      ,[age]
      ,[gender]
      ,[item_purchased]
      ,[category]
      ,[purchase_amount]
      ,[location]
      ,[size]
      ,[color]
      ,[season]
      ,[review_rating]
      ,[subscription_status]
      ,[shipping_type]
      ,[discount_applied]
      ,[previous_purchases]
      ,[payment_method]
      ,[frequency_of_purchases]
      ,[age_group]
      ,[purchase_frequency_days]
  FROM [customer_behavior].[dbo].[customer_behavior]
  -- Q1: what is the total revenue generated by male vs female
  
  select gender , sum(purchase_amount) as revenue 
  FROM [customer_behavior].[dbo].[customer_behavior]
  group by gender ;

  -- Q2 which customers used a discount but still spent more than average purchase amount 
  select customer_id,purchase_amount
  FROM [customer_behavior].[dbo].[customer_behavior]
  where discount_applied='Yes' and purchase_amount>=( select avg(purchase_amount)FROM [customer_behavior].[dbo].[customer_behavior]); 
  

  --Q3 which are the top 5 products with the highest average review rating 
  select top 5  item_purchased ,round(avg(review_rating),2) as avg_review_rating
  FROM [customer_behavior].[dbo].[customer_behavior]
  group by item_purchased
  order by avg_review_rating desc
 ;

 --Q4 compare the avg purchase_amount btw standard and express shipping 
 select shipping_type ,avg(purchase_amount) as avg_purchase_amount
 FROM [customer_behavior].[dbo].[customer_behavior]
 where shipping_type IN ('Standard','Express')
 group by shipping_type;
  

  --Q5 do subscribed customers spend more? compare total_spent and revenue

  select top 5
  subscription_status ,count(customer_id) as total_customer, AVG(purchase_amount) as avg_purchase_amount , sum(purchase_amount) as total_revenue
  FROM [customer_behavior].[dbo].[customer_behavior]
  group by subscription_status;
-- Q6 which 5 products have the heightst percentage of purchase with discount applied 
select item_purchased , round(sum(case when discount_applied = 'Yes' then 1.0 else 0.0 end)/count(*) * 100,2) as discount_rate
FROM [customer_behavior].[dbo].[customer_behavior]
group by item_purchased
order by discount_rate desc;


-- Q7 segment customers into new, returning , loyal based on their total number of previous purchases , and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
case
    when previous_purchases =1  then 'new'
    when previous_purchases between 2 and 10 then 'returning'
    else 'loyal'
    end as customer_segment

FROM [customer_behavior].[dbo].[customer_behavior] 
)
select customer_segment, count(*) as "Number of Customers"

from customer_type
group by customer_segment;

-- Q8 what are the top 3 most purchased products within each category 
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) desc) as item_rank
from [customer_behavior].[dbo].[customer_behavior]
group by category, item_purchased)

select item_rank , category, item_purchased, total_orders 
from item_counts
where item_rank <= 3;

--Q9: Are customers who are frequent buyers (more than 5 previous purchases) are more likely to subscribe?!
select subscription_status, 
count(customer_id) as repeat_buyers 
from [customer_behavior].[dbo].[customer_behavior]
where previous_purchases > 5
group by subscription_status;

--Q10: what is the revenue contribution of each age group?
select age_group , count(customer_id) as total_customers , sum(purchase_amount) as revenue 
from [customer_behavior].[dbo].[customer_behavior]
group by age_group
order by revenue desc;